### ISSUE TITLE
Module does not support price sets which are defined in quick mode 

### ISSUE THREAD

**Issue by urlisse** [coopsymbiotic/biz.jmaconsulting.cdntaxcalculator#1]
When editing a participant form for an event whose price sets have been defined in quick mode, the following message is shown where the line items should normally appear :

>  Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
> Expected one Event but found 0

The erroneous assignment happens on line 164 of cdntaxcalculator.php. The module falsely assumes that the $form passed as parameter is an event form because it doesn't plan for a case when $form_name == 'CRM_Event_Form_Participant'. It therefore assigns the participant_id as the event_id, which eventually causes the error mentioned above.

A quick fix to get rid of the error message would be to apply the following patch in order to fetch the event_id the same way it does with the CRM_Event_Form_ParticipantFeeSelection form.

[cdntaxcalculator-1-patch.txt](https://github.com/coopsymbiotic/biz.jmaconsulting.cdntaxcalculator/files/1616284/cdntaxcalculator-1-patch.txt)

However, this solution doesn't appear to be complete since the line items still do not appear next to the form on the participant edit view. 

@mathieu, tu peux trouver un log de l'erreur dans /var/aegir/platforms/civicrm-4.7/sites/communaute.cdclongueuil.org/files/civicrm/ConfigAndLog/CiviCRM.19a90419cf24acd3475b9b9b.log

**Comment by mlutfy** [comment]
I committed this patch, based on yours: https://github.com/coopsymbiotic/biz.jmaconsulting.cdntaxcalculator/commit/0bbf117cdb1d84a93fd991e547b5c9e89ce5672e

It makes it possible to open the edit popup, but I did not test further. I think that CiviCRM should recalculate the taxes on `civicrm_post`, but that might only be working for Contributions, not Events? It might also be necessary to add a call to the `buildAmount` hook in the postProcess.

https://gist.github.com/mlutfy/3c3d74d24c5853bf39d29830bc8e93d8
